# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af07c85b1c3584183d8b1d44a6f40b62fb6043481d524680b84bf4699323b9aad1367aa0cc0044b4c1ae2dea31fa77c052feb8c704aa01529733ab35dc443e5e

test:
  secret_key_base: fafc5eb296b45b53a8e420f3e7474f728494d5faf77270cdd513e7e2c3361a4a17e04e1bf58563ee620fc8738dbc90ce875800b8379ba2477e74d11469bd7e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
